kiplot:
  version: 1

preflight:
  run_erc: true
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false
  filters:
    - filter_msg: 'Pin connected to other pins, but not driven by any pin'
      error_number: 3
      regexp:  '(Power input) of component'

outputs:
  - name: 'Print Schema as PDF'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: schematics
    options:
      output: '%p-Schematic.%x'

  - name: 'Pront Schema as SVGs'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: schematics
    options:
      output: '%p-Schematic.%x'

  - name: 'print board'
    comment: "Print board (PDF)"
    type: pdf_pcb_print
    layers: 'all'
    dir: layout
    options:
      output: '%p-Board.%x'

  # PcbDraw - Beautiful 2D PCB render:
  # Uses configurable colors.
  # Can also render the components if the 2D models are available
  - name: 'plot images of pcb TOP'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'layout'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: false
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)] list of components to highlight
      # highlight:
      # [list(string)] list of libraries
      libs: ['/opt/pcbdraw/lib']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i.%x'] name for the generated file . Affected by global options
      output: '%f-Board_%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [string|list(string)] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/opt/pcbdraw/pcbdraw/styles/jlcpcb-green-enig.json'
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'visible'

  - name: 'plot images of pcb BOTTOM'
    comment: 'Exports the PCB as a 2D model (SVG, PNG or JPG).'
    type: 'pcbdraw'
    dir: 'layout'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: true
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)] list of components to highlight
      # highlight:
      # [list(string)] list of libraries
      libs: ['/opt/pcbdraw/lib']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i.%x'] name for the generated file . Affected by global options
      output: '%f-Board_%i.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [string|list(string)] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/opt/pcbdraw/pcbdraw/styles/jlcpcb-green-enig.json'
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'visible'
